import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { PLATFORM_VERSION, parseManifest, type PluginManifest } from "@constellation/plugin-sdk";

export interface GeneratePluginOptions {
  /**
   * Absolute path to the `plugins/` directory to scaffold into. Defaults to
   * `<repo root>/plugins`, where repo root is discovered by walking up from
   * `process.cwd()` for `pnpm-workspace.yaml`. Tests pass an explicit temp
   * dir here instead of touching the real `plugins/` tree.
   */
  pluginsRoot?: string;
  /** Overwrite an existing plugin directory. Defaults to false (throws if present). */
  force?: boolean;
}

export interface GeneratePluginResult {
  id: string;
  dir: string;
  manifest: PluginManifest;
}

/** Convert an arbitrary plugin name ("My Cool Plugin", "MyCoolPlugin") to kebab-case. */
export function toKebabCase(name: string): string {
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

/** Walk up from `startDir` looking for the monorepo root (marked by pnpm-workspace.yaml). */
export function findRepoRoot(startDir: string): string {
  let dir = startDir;
  for (let i = 0; i < 20; i++) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break; // reached filesystem root
    dir = parent;
  }
  throw new Error(`Could not locate the monorepo root (pnpm-workspace.yaml) above ${startDir}`);
}

/**
 * Scaffold a new plugin under `plugins/<kebab-name>/`: manifest, package.json,
 * tsconfig.json mirroring `plugins/hello-world`, a `definePlugin` stub, and a
 * basic test. The manifest is validated with the SDK's `parseManifest` BEFORE
 * anything is written to disk — a scaffold that can't satisfy the platform's
 * own contract must never land on the filesystem.
 */
export function generatePlugin(name: string, options: GeneratePluginOptions = {}): GeneratePluginResult {
  const id = toKebabCase(name);
  if (!id) {
    throw new Error(`"${name}" doesn't produce a valid plugin id (kebab-case, starts with a letter)`);
  }

  const pluginsRoot = options.pluginsRoot ?? join(findRepoRoot(process.cwd()), "plugins");
  const dir = join(pluginsRoot, id);
  if (existsSync(dir) && !options.force) {
    throw new Error(`Plugin directory already exists: ${dir} (pass --force to overwrite)`);
  }

  const manifest = parseManifest({
    manifestVersion: 2,
    id,
    name,
    version: "0.1.0",
    description: "",
    author: "",
    license: "UNLICENSED",
    minPlatformVersion: PLATFORM_VERSION,
    permissions: [],
    requiredServices: [],
    navigation: [{ id: `${id}-home`, label: name, path: `/${id}`, order: 100, requiresPermissions: [] }],
    routes: [],
    featureFlags: [],
    settings: [],
    jobs: [],
    entry: "dist/index.js",
    healthCheck: "/health",
    translations: [],
  });

  mkdirSync(join(dir, "src"), { recursive: true });
  writeFileSync(join(dir, "plugin.manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(join(dir, "package.json"), packageJsonFor(id));
  writeFileSync(join(dir, "tsconfig.json"), tsconfigContents);
  writeFileSync(join(dir, "src", "index.ts"), indexTsFor(id));
  writeFileSync(join(dir, "src", "index.test.ts"), testTsFor(id));

  return { id, dir, manifest };
}

function packageJsonFor(id: string): string {
  const pkg = {
    name: `@constellation/plugin-${id}`,
    version: "0.1.0",
    description: "",
    private: true,
    type: "module",
    main: "dist/index.js",
    scripts: {
      build: "tsc -p tsconfig.json",
      typecheck: "tsc --noEmit",
      test: "vitest run",
      clean: "rimraf dist .turbo",
    },
    dependencies: {
      "@constellation/plugin-sdk": "workspace:*",
    },
    devDependencies: {
      rimraf: "^6.0.1",
      typescript: "^5.7.2",
      vitest: "^2.1.8",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

// Mirrors plugins/hello-world/tsconfig.json exactly: `declaration` AND
// `declarationMap` must both be off, or `tsc` errors (declarationMap
// requires declaration). See MASTER_PLAN.md §9.
const tsconfigContents = `{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "outDir": "dist",
    "rootDir": "src",
    "declaration": false,
    "declarationMap": false
  },
  "include": ["src"],
  "exclude": ["dist", "node_modules"]
}
`;

function indexTsFor(id: string): string {
  return `import { definePlugin, type HealthResult, type PluginContext } from "@constellation/plugin-sdk";

/**
 * The ${id} plugin. Generated by \`generate-plugin\` — implement the lifecycle
 * hooks you need here and declare the rest (routes, nav, permissions,
 * settings, ...) in plugin.manifest.json.
 */
export default definePlugin({
  register(ctx: PluginContext): void {
    ctx.logger.info("${id} registered");
  },

  enable(ctx: PluginContext): void {
    ctx.logger.info("${id} enabled");
  },

  health(): HealthResult {
    return { status: "ok" };
  },
});
`;
}

function testTsFor(id: string): string {
  return `import { describe, expect, it } from "vitest";
import type { PluginContext } from "@constellation/plugin-sdk";
import plugin from "./index.js";

function fakeContext(): PluginContext {
  return {
    pluginId: "${id}",
    logger: {
      debug: () => undefined,
      info: () => undefined,
      warn: () => undefined,
      error: () => undefined,
      child(): PluginContext["logger"] {
        return fakeContext().logger;
      },
    },
    config: {
      get: () => undefined,
      getOrThrow: () => {
        throw new Error("config not available in tests");
      },
      isFeatureEnabled: () => false,
    },
    events: {
      emit: () => undefined,
      on: () => undefined,
      onPlatform: () => undefined,
    },
    getPrincipal: () => undefined,
  };
}

describe("${id} plugin", () => {
  it("register() does not throw", () => {
    expect(() => plugin.register?.(fakeContext())).not.toThrow();
  });

  it("health() reports ok", () => {
    expect(plugin.health?.(fakeContext())).toEqual({ status: "ok" });
  });
});
`;
}
